### ISSUE TITLE
Auxiliary devices in SOF break SOFCARD

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#466] opened 2020-10-23 06:36 UTC
Auxiliary devices in SOF https://github.com/thesofproject/linux/pull/2501 break most SOF TEST https://sof-ci.01.org/sofpr/PR3545/build7503/devicetest/

After some quick check root cause to be SOFCARD
```
ubuntu@sh-cml-mantis-hda-03:~$ grep 'sof-[a-z]' /proc/asound/cards|awk '{print $1;}'
0
2
ubuntu@sh-cml-mantis-hda-03:~$ cat /proc/asound/cards
 0 [sofprobes      ]: sof-probes - sof-probes
                      DellInc.-Inspiron5590--
 1 [Device         ]: USB-Audio - USB Audio Device
                      C-Media Electronics Inc. USB Audio Device at usb-0000:00:14.0-1, full speed
 2 [sofhdadsp      ]: sof-hda-dsp - sof-hda-dsp
                      DellInc.-Inspiron5590--
```

**Comment by xiulipan** [comment] 2020-10-23 06:38
@aiChaoSONG Could you help to have a quick fix for this?
@ranj063 Why there is a new card for the probe? I do not see any new PCM. Will the name be changed? Can we just ignore the card by probe keyword.

**Comment by aiChaoSONG** [comment] 2020-10-23 06:41
@xiulipan I just want to exclude sof-probes with another grep, but we need @ranj063 to confirm on the name.

**Comment by xiulipan** [comment] 2020-10-23 06:41
@aiChaoSONG Let's wait for @ranj063 confirmation. I see https://github.com/thesofproject/linux/pull/2501 is closed now, maybe it is not the final solution.

**Comment by fredoh9** [comment] 2020-10-23 17:45
sof-probes card can be any number by probing order. We need to ignore.
2501 is final solution but not going to merge to topic/sof-dev now.  Acillary bus should be upstream first and then this will be merged to our github project. We should be ready with the change.

**Comment by plbossart** [comment] 2020-10-23 17:51
Agree with @fredoh9 we need to have sof-test ready (and sof-ci is relevant) for the addition of probes. 

Let's not repeat the fiasco I started with the ACPI transition...

**Comment by ranj063** [comment] 2020-10-23 20:39
> @xiulipan I just want to exclude sof-probes with another grep, but we need @ranj063 to confirm on the name.

Im sorry I dont understand what you mean by ignore. We want to test probes as well. If the problem is that we assume that the pcm devices in topology will always be in Card 0, we need to fix that logic.

**Comment by ranj063** [comment] 2020-10-23 20:40
> @aiChaoSONG Let's wait for @ranj063 confirmation. I see [thesofproject/linux#2501](https://github.com/thesofproject/linux/pull/2501) is closed now, maybe it is not the final solution.

the aux bus stuff is being reviewed upstream and will land sof-dev after it is accepted upstream

**Comment by aiChaoSONG** [comment] 2020-10-26 02:37
@ranj063 Thanks for the confirmation, I can add a grep to ignore the sof-probes now.

**Comment by aiChaoSONG** [comment] 2021-01-26 06:49
confirmed fixed by @xiulipan ,close

**Closed by aiChaoSONG** 2021-01-26 06:49 UTC
Labels: bug
