### ISSUE TITLE
[bug] Need add timed for actual playback and recording lengths, e.g. aplay/arecord 10s should take min 10s and max 11s.?

### ISSUE THREAD

**Issue by ClarexZhou** [thesofproject/sof-test#256] opened 2020-06-16 02:09 UTC
Check details in https://github.com/thesofproject/linux/issues/1876#issuecomment-603092945

Also it is the application behavior that record with 48KHz will record 3 times length.

**Comment by lgirdwood** [comment] 2020-06-16 07:54
10s of Playbcak/capture using "-d" will take exactly 10secs (+plus negible overhed for opening & closing the device)

**Comment by dbaluta** [comment] 2020-06-16 08:25
@lgirdwood i wonder exactly how "negligible" is the overhead at open.

Besides opening the devices (if device is runtime suspended) then we will also load and boot the firmware.

**Comment by lgirdwood** [comment] 2020-06-16 08:51
@dbaluta a few hundrred msecs at most, but the test could pre-open the device first (to keep DSP in D0)  to cancel out any loading overhead. The ideal solution is to do the timing check in aplay.

**Comment by libinyang** [comment] 2020-06-16 09:28
You can use the command `time` to check the real/user/sys time, e.g. `time aplay -Dhw:0 xxx`
For the issue https://github.com/thesofproject/linux/issues/1876, I guess maybe the sample rate 16KHz is not supported when playback. You can use `aplay -Dplughw:0 ` to check the length.

**Comment by lgirdwood** [comment] 2020-06-16 10:00
@libinyang cmd line does not rule out device setup time, measring from stream start -> end in aplay is correct. Perhaps the aplay -d switch could report if tme taken did not match the time requested. Seems a simple chnage.

**Comment by libinyang** [comment] 2020-06-16 10:39
> @libinyang cmd line does not rule out device setup time, measring from stream start -> end in aplay is correct. Perhaps the aplay -d switch could report if tme taken did not match the time requested. Seems a simple chnage.

Does Clare want to measure how long the playback takes? For example, she plays 10s wav file, and want to measure whether it really takes 10s to finish the playback? `aplay -d 10` will always take 10s  or so to play the wav file.

**Comment by ClarexZhou** [comment] 2020-06-28 05:58
Yes. I want add time for aplay -d 10 to ensure the actual time taken for stream. 

@aiChaoSONG @xiulipan  could you help to check on this?

**Comment by aiChaoSONG** [comment] 2020-06-28 06:07
@ClarexZhou  I think we already have such case with -d parameter equals 10.  check usage of https://github.com/thesofproject/sof-test/blob/master/test-case/check-playback.sh

**Comment by ClarexZhou** [comment] 2020-06-28 06:16
i mean using ```time aplay -d 10``` command with ```time``` to ensure the actual execution time.  To find issue like thesofproject/linux#1876

**Comment by xiulipan** [comment] 2021-01-26 07:22
duplicated with https://github.com/thesofproject/sof-test/issues/353

**Comment by marc-hb** [comment] 2023-06-22 01:24
closing as duplicate of
- #353

**Closed by marc-hb** 2023-06-22 01:24 UTC
Labels: type:bug, type:enhancement
