### ISSUE TITLE
[BUG] filter out I/O error on TGLU_RVP_SDW?

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#874] opened 2022-03-08 17:31 UTC
https://sof-ci.01.org/linuxpr/PR3338/build7304/devicetest/?model=TGLU_RVP_SDW&testcase=verify-kernel-boot-log

````
===========================>>
[    4.941522] kernel: I/O error, dev loop14, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
<<===========================
````

**Comment by plbossart** [comment] 2022-03-08 22:54
Also on CML_RVP:
https://sof-ci.sh.intel.com/#/result/planresultdetail/10800?model=CML_RVP_SDW&testcase=verify-kernel-boot-log
````
[   14.950119] kernel: I/O error, dev loop0, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
````

**Comment by marc-hb** [comment] 2022-03-09 22:30
https://sof-ci.01.org/sofpr/PR5501/build12279/devicetest/?model=CML_RVP_SDW&testcase=verify-kernel-boot-log

**Comment by marc-hb** [comment] 2022-03-11 07:42
I can reproduce with a simple `apt remove snapd; apt install snapd` which confirms this is snapd-related. So I think this can be ignored, submitted in #878. snapd is the only loopback user AFAIK. 

For some reason `systemctl` cannot reproduce. There are two snapd services in systemctl, snapd.seeded and snapd.socket/service. Maybe this could be reproduced by restarting both with a specific timing?

**Comment by keqiaozhang** [comment] 2022-03-17 00:59
New loop ID happened on TGLU_RVP_SDW。
```
 kernel: I/O error, dev loop14, sector 0 op 0x0:(READ) flags 0x80700 phys_seg 1 prio class 0
```

**Comment by marc-hb** [comment] 2022-03-17 01:03
@keqiaozhang the fix is very simple:
```
snap list
snap sudo remove <everything>
```

**Comment by marc-hb** [comment] 2022-03-17 01:12
```shell
remove_all_snaps () 
{ 
    # need multiple iterations because of dependencies
    while test -n "$(snap list)"; do
        snap list | tail +2 | awk '{print $1}' | while read -r p; do
            sudo snap remove $p;
        done;
    done
}
```

**Comment by keqiaozhang** [comment] 2022-03-17 04:24
I have removed the snaps on those devices, let keep monitor this issue in CI for a few days.

**Comment by keqiaozhang** [comment] 2022-03-30 02:19
This problem was not seen in CI within 2 weeks, closing this issue.

**Closed by keqiaozhang** 2022-03-30 02:19 UTC
Labels: bug
