### ISSUE TITLE
[BUG] multiple-pause-resume.sh should be deterministic

### ISSUE THREAD

**Issue by lyakh** [thesofproject/sof-test#796] opened 2021-10-29 07:32 UTC
**Describe the bug**
multiple-pause-resume.sh runs audio playback and capture while pausing and releasing streams at random times. This makes testing less reproducible.

**Expected behavior**
Random times should be replaced with deterministic ones.

**Proposed fix**
I propose to replace random times with a list of "pseudo-random" but fixed intervals. We could either use the pseudo-random number generator but with a fixed seed, or we can have a file with a list of "randomly picked up" prime numbers to be used as those pause-resume delays.

FYI @lgirdwood @marc-hb

**Comment by marc-hb** [comment] 2021-10-30 05:36
Duplicate of #694 ?

**Comment by marc-hb** [comment] 2021-11-12 23:19
I'm assuming this is a duplicate of #694, explain and re-open if not.

**Closed by marc-hb** 2021-11-12 23:19 UTC
