### ISSUE TITLE
i915 error during suspend/resume

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof-test#764] opened 2021-09-10 03:26 UTC
[ 945.548337] kernel: i915 0000:00:02.0: [drm] *ERROR* Atomic update failure on pipe A (start=184 end=185) time 149 us, min 1073, max 1079, scanline start 1071, end 1081

Showed up randomly in the suspend/resume test on TGL HDA device. 
Logs here: https://sof-ci.01.org/sofpr/PR4702/build10276/devicetest/

**Comment by YongAnLu00** [comment] 2021-09-15 07:46
duplicate of #753

**Closed** 2021-09-15 14:58 UTC
