### ISSUE TITLE
[Enhancement][log] log collection with journalctl

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#638] opened 2021-03-26 06:51 UTC
We are still using /var/log/kern.log for log collection, this file is not exist on ChromeOS and Fedora, which makes sof-test not flexible. Replace current log collection with journalctl.

Issue migrate from gitlab: 
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/466
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/477
- https://gitlab.devtools.intel.com/sof-ci/sofcitest/issues/500

**Comment by mengdonglin** [comment] 2021-04-28 03:11
Duplicate of #466 and #477. Close this.

**Closed by mengdonglin** 2021-04-28 03:11 UTC
Labels: P1, bug, enhancement
