### ISSUE TITLE
[BUG] aplay processes hang even after kill -9 in LNLM_RVP_HDA

### ISSUE THREAD

**Issue by fredoh9** [thesofproject/sof-test#1129] opened 2023-11-16 19:16 UTC
**Describe the bug**

Running multiple-pipeline-playback with 2 pipelines, 0 and 31. But failed with process count mismatch. Looks like aplay from previous iteration still not killed
`2023-11-16 12:48:07 UTC [REMOTE_ERROR] Running process count is 4, but 2 is expected`

```
...
2023-11-16 12:47:59 UTC [REMOTE_INFO] ===== Testing: (Loop: 17/50) =====
2023-11-16 12:47:59 UTC [REMOTE_INFO] /home/ubuntu/sof-test/test-case/multiple-pipeline.sh will use topology /usr/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg to run the test case
2023-11-16 12:47:59 UTC [REMOTE_INFO] Pipeline list to ignore is specified, will ignore 'pcm=HDA Digital' in test case
2023-11-16 12:47:59 UTC [REMOTE_INFO] Run command to get pipeline parameters
2023-11-16 12:47:59 UTC [REMOTE_COMMAND] sof-tplgreader.py /usr/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg -f 'type:playback  & ~pcm:HDMI' -b ' pcm:HDA Digital' -s 0 -e
2023-11-16 12:47:59 UTC [REMOTE_INFO] Testing: HDA Analog [hw:0,0]
2023-11-16 12:47:59 UTC [REMOTE_COMMAND] aplay   -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
2023-11-16 12:47:59 UTC [REMOTE_INFO] Testing: Deepbuffer HDA Analog [hw:0,31]
2023-11-16 12:47:59 UTC [REMOTE_INFO] wait 0.5s for aplay_opts()
2023-11-16 12:47:59 UTC [REMOTE_COMMAND] aplay   -D hw:0,31 -c 2 -r 48000 -f S16_LE /dev/zero -q
2023-11-16 12:47:59 UTC [REMOTE_INFO] checking pipeline status
2023-11-16 12:47:59 UTC [REMOTE_INFO] Letting playback/capture run for 5s
2023-11-16 12:48:04 UTC [REMOTE_INFO] checking pipeline status again
2023-11-16 12:48:05 UTC [REMOTE_COMMAND] pkill -9 aplay arecord
declare -- cmd="journalctl_cmd --since=@1700138878"
2023-11-16 12:48:06 UTC [REMOTE_INFO] ===== Testing: (Loop: 18/50) =====
2023-11-16 12:48:06 UTC [REMOTE_INFO] /home/ubuntu/sof-test/test-case/multiple-pipeline.sh will use topology /usr/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg to run the test case
2023-11-16 12:48:06 UTC [REMOTE_INFO] Pipeline list to ignore is specified, will ignore 'pcm=HDA Digital' in test case
2023-11-16 12:48:06 UTC [REMOTE_INFO] Run command to get pipeline parameters
2023-11-16 12:48:06 UTC [REMOTE_COMMAND] sof-tplgreader.py /usr/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg -f 'type:playback  & ~pcm:HDMI' -b ' pcm:HDA Digital' -s 0 -e
2023-11-16 12:48:06 UTC [REMOTE_INFO] Testing: HDA Analog [hw:0,0]
2023-11-16 12:48:06 UTC [REMOTE_COMMAND] aplay   -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
2023-11-16 12:48:06 UTC [REMOTE_INFO] Testing: Deepbuffer HDA Analog [hw:0,31]
2023-11-16 12:48:06 UTC [REMOTE_INFO] wait 0.5s for aplay_opts()
2023-11-16 12:48:06 UTC [REMOTE_COMMAND] aplay   -D hw:0,31 -c 2 -r 48000 -f S16_LE /dev/zero -q
2023-11-16 12:48:06 UTC [REMOTE_INFO] checking pipeline status
2023-11-16 12:48:07 UTC [REMOTE_ERROR] Running process count is 4, but 2 is expected
19586 aplay -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
19594 aplay -D hw:0,31 -c 2 -r 48000 -f S16_LE /dev/zero -q
19698 aplay -D hw:0,0 -c 2 -r 48000 -f S16_LE /dev/zero -q
19706 aplay -D hw:0,31 -c 2 -r 48000 -f S16_LE /dev/zero -q
2023-11-16 12:48:07 UTC [REMOTE_INFO] Starting func_exit_handler(1)
2023-11-16 12:48:07 UTC [REMOTE_ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2023-11-16 12:48:07 UTC [REMOTE_ERROR]  func_error_exit()  @  /home/ubuntu/sof-test/test-case/multiple-pipeline.sh
2023-11-16 12:48:07 UTC [REMOTE_ERROR]  ps_checks()  @  /home/ubuntu/sof-test/test-case/multiple-pipeline.sh:146
2023-11-16 12:48:07 UTC [REMOTE_ERROR]  main()  @  /home/ubuntu/sof-test/test-case/multiple-pipeline.sh:193
```

**To Reproduce**
Found in LNLM_RVP_HDA with multiple-pipeline-playback.

TPLG=/lib/firmware/intel/sof-ace-tplg/sof-hda-generic-4ch.tplg MODEL=LNLM_RVP_HDA SOF_TEST_INTERVAL=5 ~/sof-test/test-case/multiple-pipeline.sh -f p -l 50

With above command, it will fail 100% but need some iterations.

**Comment by keqiaozhang** [comment] 2023-12-08 06:23
Seems like a duplicate of https://github.com/thesofproject/linux/issues/4678.

**Comment by marc-hb** [comment] 2024-08-01 18:43
Closing as duplicate

**Closed by marc-hb** 2024-08-01 18:43 UTC
