### ISSUE TITLE
[Impovement] Pulseaudio start to be managed by systemd  on Ubuntu 20.04

### ISSUE THREAD

**Issue by aiChaoSONG** [thesofproject/sof-test#121] opened 2020-03-16 08:36 UTC
Pulseaudio start to be managed by systemd  on Ubuntu2004, Our current scripts to disable/enable pulseaudio will need improvement. set up the issue to track this change.

**Comment by aiChaoSONG** [comment] 2020-03-30 02:24
close for now, when we switch to Ubuntu 2004, if need reopen later.

**Comment by marc-hb** [comment] 2021-07-02 22:55
See related #728

**Comment by marc-hb** [comment] 2021-07-02 22:56
Duplicate of #91 which has more information

**Closed by marc-hb** 2021-07-02 22:56 UTC
Labels: pulseaudio
