### ISSUE TITLE
check-sof-logger need to report fail is no valid log shows

### ISSUE THREAD

**Issue by xiulipan** [thesofproject/sof-test#298] opened 2020-07-29 05:52 UTC
From latest test result. logger on legacy platform is not working but the test result of check-sof-logger still show pass. Need to fix the issue in check-sof-logger

```
2020-07-29 02:09:31 UTC [REMOTE_INFO] Found file: /usr/bin/sof-logger 96b4a1605636506fab8cfbac4396f7ce
2020-07-29 02:09:31 UTC [REMOTE_INFO] Checking ldc File: /etc/sof/sof-bdw.ldc ...
2020-07-29 02:09:31 UTC [REMOTE_INFO] Found file: /etc/sof/sof-bdw.ldc 6d96f9315129a366644043bbaab6a96b
2020-07-29 02:09:31 UTC [REMOTE_INFO] Try to dump the dma trace log via sof-logger ...
2020-07-29 02:09:31 UTC [REMOTE_COMMAND] sudo /usr/bin/sof-logger -t -l /etc/sof/sof-bdw.ldc -o /home/ubuntu/sof-test/logs/check-sof-logger/2020-07-29-10:09:31-5838/logger.data.log 2> /home/ubuntu/sof-test/logs/check-sof-logger/2020-07-29-10:09:31-5838/logger.error.log &
2020-07-29 02:09:33 UTC [REMOTE_COMMAND] sudo pkill -9 sof-logger
2020-07-29 02:09:34 UTC [REMOTE_INFO] Log data BEG>>
         TIMESTAMP              DELTA C# COMPONENT          LOCATION                      CONTENT
2020-07-29 02:09:34 UTC [REMOTE_INFO] <
```

**Comment by mengdonglin** [comment] 2020-07-31 00:08
Same requirement as https://github.com/thesofproject/sof-test/issues/297

**Comment by marc-hb** [comment] 2021-04-27 04:40
Duplicate of #297, closing

**Closed** 2022-01-21 17:56 UTC
Labels: state:duplicate, type:enhancement, P1, area:SOF logging
