### ISSUE TITLE
Missing FW logs on CI failures

### ISSUE THREAD

**Issue by lgirdwood** [thesofproject/sof-test#294] opened 2020-07-24 10:53 UTC
I'm seeing some recent CI failures where sof-logger and error logs are empty. Not sure if this is FW issue or CI issue atm.
 
Please see the failure messages here.
https://sof-ci.01.org/sofpr/PR3214/build6680/devicetest/

**Comment by plbossart** [comment] 2020-07-30 19:18
@lgirdwood fixed by reverting recent scheduling changes: https://github.com/thesofproject/sof/pull/3245

Of course it's a terrible fix but at least this restores the trace functionality. See issues #296 and #297 added to check the presence of a trace.

Now that the kernel CI is all green, we need a PR to re-check @jajanusz 's work and figure out why it broke the trace.

**Comment by mwasko** [comment] 2020-08-03 08:06
> @lgirdwood fixed by reverting recent scheduling changes: [thesofproject/sof#3245](https://github.com/thesofproject/sof/pull/3245)

@plbossart the revert has nothing to do with the problem fix. The issue just didn't reproduce on next CI run. I have consulted this with @zrombel and the reason why sporadically there is no logs in CI failed tests it is because the specific test was not run at all (network connectivity issue).

We are working now to improve our CI to either re-run the test in such situation or at least to correctly report test result as 'not run' instead of failure.

**Comment by mwasko** [comment] 2020-08-04 11:26
Apparently we have two separate issues related to missing logs, one specific to BYT CI tests that was resolved by the revert done @plbossart and second issue related to FW CI where there is no logs in case when test was not executed due to connectivity error: https://sof-ci.01.org/sof-pr-viewer/#/build/PR3245/build5301944

**Comment by xiulipan** [comment] 2020-09-24 08:04
Issue fixed with sof pr https://github.com/thesofproject/sof/pull/3278

**Closed by xiulipan** 2020-09-24 08:04 UTC
