### ISSUE TITLE
[FEATURE] Add test for probes

### ISSUE THREAD

**Issue by ranj063** [thesofproject/sof-test#920] opened 2022-06-14 16:38 UTC
**Is your feature request related to a problem? Please describe.**
Enable testing the probes feature in the SOF firmware.

**Describe the solution you'd like**
Introduce 'probe-based loopback' where the last buffer before the DAI would be added to a probe point. That would capture the last data and we could feed the information in alsa-bat with some changes for the compressed data/parsing of payload.

**Comment by kv2019i** [comment] 2022-06-16 12:57
Duplicate of https://github.com/thesofproject/sof-test/issues/922 @jsarha

**Comment by marc-hb** [comment] 2022-06-16 22:55
Technically 920 came before 922 so 922 is the duplicate but 922 has more details so closing this one :-)

**Closed by marc-hb** 2022-06-16 22:55 UTC
