### ISSUE TITLE
[BUG] sof-logger resisted pkill -INT, using -KILL

### ISSUE THREAD

**Issue by marc-hb** [thesofproject/sof-test#385] opened 2020-09-18 02:11 UTC
https://github.com/thesofproject/sof-test/pull/373 was merged because https://sof-ci.01.org/softestpr/PR373/build182/devicetest was all green. However almost all tests were failing because the sof-logger resisted kill -INT. To make it worse I misused `exit_status=2` which has the special meaning Not Applicable which means no error and everything is green.

**Comment by mengdonglin** [comment] 2020-09-28 08:12
Keep this issue open before we root cause if this is a bug of sof-logger or test case. 
- If this is an sof-logger issue, will close this issue and report a bug in SOF repo.
- If this is a test case issue, we will use PR #401 and close this issue.

**Comment by marc-hb** [comment] 2020-09-28 14:43
I believe this has been fixed by #382 `hijack.sh: switch first attempt to stop the logger from -INT to -TERM`, closing.

**Closed** 2020-10-19 07:07 UTC
Labels: P2, bug
